title: Hello, World
author:
  name: Z
  email: abc@dklz.ca
description: >
  Less is more.

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

remote_theme: jekyll/minima

minima:
  skin: auto
