title: Hello, World
author:
  name: lz
  email: abc@dklz.ca
description: >
  Less is More.

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

remote_theme: jekyll/minima

minima:
  skin: solarized
