title: Hello, World
author:
  name: Vx
  email: helloworld@dklz.ca
description: >
  Less is more.

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

remote_theme: jekyll/minima

minima:
  skin: auto
